### ISSUE TITLE
Error occurred in the middle of building kernel

### ISSUE THREAD

**Issue by sind9ood** [kentonl/e2e-coref#5]
Got this error when i tried running "setup_all.sh"
I'm using Mac and uncommented right line for mac. 
Using "virtualenv" to setup environment where tensorflow version is 1.0.0rc2.

In file included from coref_kernels.cc:5:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/shape_inference.h:21:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/node_def_util.h:23:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/attr_value_util.h:22:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/partial_tensor_shape.h:21:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:4:
In file included from /Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/Tensor:149:
/Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not
      more specialized than the primary template [-Winvalid-partial-specialization]
class TensorStorage<T, FixedDimensions, Options_>
      ^
/Users/jhshin/tensorflow/lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: template is declared here
template<typename T, typename Dimensions, int Options_> class TensorStorage;

**Comment by sind9ood** [comment]
Problem solved after updating tensorflow to 1.3.0
